### ISSUE TITLE
[Question] How do I code a mod?

### ISSUE THREAD

**Issue by NikeSchuh** [SuperKael/Gadget-Core#2]
Hello!

Im asking myself how do I code a mod? Is there some kind of guide? I can code Java since c# is simular to Java I want to try to code a simple mod with GadgetCore.
It would be nice if you make a Guide with steps how to code a mod for / with the api.

**Comment by SuperKael** [comment]
While I agree having a step-by-step guide would be nice, I'm not sure I will ever get around to it honestly... if you want me to help introduce you to modding personally, I can do that on Discord. I recommend joining the New Roguelands Discord, if you haven't already.

**Comment by cheeeeeeeeeen** [comment]
Invite to Discord: https://discord.gg/NavzQ8c

**Comment by SuperKael** [comment]
After leaving this issue open for more than four years, I think it's about time I close this. There is some information on how to make a simple mod on the Roguelands Fandom wiki, as well as some advanced guides on this GitHub's wiki pages. However, unfortunately a full-fledged guide will likely never come, as I simply do not have the time to write such a thing. I will always be available in the Discord to help anyone who needs it though.
