### ISSUE TITLE
Multiplayer, Client-Side: Host's Droids do not appear on client

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [SuperKael/Gadget-Core#3]
The host's droids do not appear in the client.

The host can see the client's droids properly, though.

**Comment by SuperKael** [comment]
Are you certain this is specific to GadgetCore? If not, I should move this to the URP repo.

**Comment by cheeeeeeeeeen** [comment]
Yeah. It is certain that this started to occur in GadgetCore, in fact the first thing we noticed upon doing a modded run.

**Comment by SuperKael** [comment]
Well alright then, I'll try to look into what could be causing this.

**Comment by SuperKael** [comment]
I'm pretty sure I ended up fixing this? After noticing this issue was still open, I spent a good while looking over all the code and I'm pretty sure this isn't still an issue.
