### ISSUE TITLE
Multiplayer Bug: Dropping Modded Chips into the world breaks

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [SuperKael/Gadget-Core#4]
Here are the issues encountered:
- Using `/givechip` from client to the host gives the host a purple box.
- Using `/givechip` from host to client gives the client a purple box.
- When the client drops a modded chip into the world, it becomes a purple box.
- When the host drops a modded chip into the world, the chip is properly displayed. A client can get this chip and properly use it.

**Comment by SuperKael** [comment]
So, uh, yeah... I finally fixed this in v2.0.3.2. I completely forgot about this. That's totally not embarrassing at all.
