### ISSUE TITLE
Multiplayer Bug: Cannot join back after a disconnect

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [SuperKael/Gadget-Core#5]
Observations:
- Joining back into the server **__after a long game__** would instantly render the joiner to disconnect instantly. The joiner can see the background where the world is being initialized tho.
- Closing down the server and rehosting without closing the game works can let the joiner join back again, but the names are not anymore being displayed.
- There is an exception regarding this one in Unity Log.

**Comment by NikeSchuh** [comment]
I have the same issue

**Comment by SuperKael** [comment]
Hm, this does seem like a pretty troublesome issue. However, saying "there is an exception regarding this one in Unity Log" is useless to me. If someone can actually get me the specific exception, or the whole log, ideally from both the host and the client, I will try to fix this post-haste.

**Comment by SuperKael** [comment]
Closing due to lack of necessary information. Besides, since so many updates have passed, maybe I fixed this at some point without realizing?
