### ISSUE TITLE
Modding: Patching with ItemStandScript.GetChipName

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [SuperKael/Gadget-Core#6]
`ItemStandScript.GetChipName` is apparently returning -1 (`int id` parameter in Harmony Prefix) on a modded chip.

`ItemStandScript.GetChipCost` works properly though.

**Comment by SuperKael** [comment]
I have now fixed this in v2.0.3.2. Back when this issue was first reported, I remember struggling so hard trying to figure this out. Now, I looked back at it earlier today, and almost immediately realized the issue. I guess that means I have grown.
